name = "midterm-results-api"
main = "src/index.js"
compatibility_date = "2026-07-01"

[[d1_databases]]
binding = "DB"
database_name = "midterm-results-db"
database_id = "39cd815e-64a2-4c51-b773-0f69dc34580d"

[vars]
# เปลี่ยนเป็น URL ของ GitHub Pages เมื่อขึ้น production เพื่อจำกัด origin เช่น
# ALLOWED_ORIGIN = "https://entclick88.github.io"
ALLOWED_ORIGIN = "*"
